phpList/core

composer.json, grumphp.yml
Adding a PR as a suggestion to seriusly embrace PSR-2 / PHP-Fig standards 
At the moment the PR does not include PHPCSfixer as a step in Grumphp. 
Suggestion: 
- evaluate PSR2 or the Symfony standard to be embraced as part of phplist
- discuss the need to force the standard compliance with Grumphp
Once the above is discussed I can modify the PR if necessary. To see the PHPCS/Grumphp report do the following
```
git clone https://github.com/bizmate/phpList.git
composer install
vendor/bin/grumphp run
```
Also a quick comment on something unrelated but still:
- why is the composer.lock file ignored? This file should be installed to avoid having composer to workout dependencies versions everytime.
- why is the phpunit.xml ignored. It would be nice to know how unit tests are running and the it …
=> Adding PSR-2 code formatting checker

composer.json, core/helper/Session.php, core/phpList.php
PHP 5.4 and PHP 5.5 have reached their end of life and thus are not
supported anymore (not even with security updates). So PHPList will
not support it anymore, either.
=> [TASK] Drop support for PHP < 5.6

.travis.yml, composer.json, core/phpList.php
We are dropping support for PHP 5.6.
=> [TASK] Make the project PHP-7-only

core/tests/AdminTest.php, core/tests/ListManagerTest.php, core/tests/ListModelTest.php, core/tests/PassTest.php, core/tests/ServicesTest.php, core/tests/SubscriberManagerTest.php, core/tests/SubscriberModelTest.php, core/tests/phpunit-bootstrap.php
The unit tests still do not pass completely as they cannot connect to any
DB on Travis yet. This will be part of a separate PR.
(And unit tests should not connect to a real database.)
=> [BUGFIX] Load an existing config file in the unit tests

.travis.yml
HHVM in PHP 7 mode breaks Composer, and HHVM in non-PHP-7 mode causes
composer to exit the install process due to the PHP version being too low.
Other big projects are dropping support for HHVM due to these issues, too.
=> [TASK] Drop HHVM support

README.md
The URLs need to have phplist4-core as the repository and packacge name,
not phpList anymore.
=> [BUGFIX] Fix the URLs in the badge links

core/services.yml
Parameters containing an "@" need to be quoted for the YAML file to be
valid (so it will still work with newer versions of symfony/yaml).
=> [BUGFIX] Quote arguments in services.yml

Classes/Domain/Model/Identity/AdministratorToken.php, Tests/Unit/Domain/Model/Identity/AdministratorTokenTest.php
This is the bare-bone model without any associations, and it is not hooked
up to Doctrine ORM yet. Both will come in later commits.
=> [FEATURE] AdministratorToken model

composer.json
As phplist4-core does not depend on any other unreleased phpList packages,
we can use the stable versions of the dependencies. This should speed up
the build as the dependencies then change only with releases of their
packages, not with each commit, allowing for better Composer caching.
=> [TASK] Use stable package dependencies

Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
This will make sure that the individual tests do not pollute each other's
environments.
=> [BUGFIX] Purge the Bootstrap instance in repository integration tests

Classes/Domain/Model/Identity/Administrator.php, Classes/Domain/Model/Identity/AdministratorToken.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
By default, the EntityManager returns a default repository, but we want to
have our own repository class instances instead.
=> [BUGFIX] Use our own repository classes

Tests/Integration/Domain/Repository/AbstractRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
This will ensure that one test cannot try to use an EntityManager from a
previous test.
=> [BUGFIX] Close the EntityManager instance in the integration tests

Classes/Domain/Model/Identity/AdministratorToken.php, Tests/Unit/Domain/Model/Identity/AdministratorTokenTest.php
The expiry should always be generated via generateExpiry, not be set
directly.
Also move the generateExpiry method to directly below setExpiry.
=> [TASK] Make AdministratorToken.setExpiry private

Classes/Domain/Model/Identity/Administrator.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/Fixtures/Administrator.csv, Tests/Unit/Domain/Model/Identity/AdministratorTest.php
We can always use the "normal" user name instead.
=> [TASK] Remove the normalized user name

composer.json
Remove all dependencies that are not needed for the current set of
automated tests.
We will re-add any dependencies once they are needed for the new code.
This will speed up the builds and the installation process.
=> [CLEANUP] Remove obsolete dependencies from composer.json

.travis.yml
This make the order of the steps for the Travis builds consistent with
the rest-api package (where this order is needed to fix the broken build).
=> [BUGFIX] Import the DB structure after the composer install

.travis.yml
This will avoid failures when getting a build on Trusty.
=> [BUGFIX] Lock the Travis builds to Precise

.github/CONTRIBUTING.md, .travis.yml, bin/console
This is the standard Symfony console plus our own Bootstrap call.
=> [FEATURE] Add the Symfony console

Classes/Core/ApplicationKernel.php, Classes/Core/ApplicationStructure.php, Classes/Core/Bootstrap.php, Tests/Integration/Core/ApplicationKernelTest.php, Tests/Integration/Core/BootstrapTest.php, Tests/Unit/Core/ApplicationStructureTest.php, Tests/Unit/Core/BootstrapTest.php
This method needs to be (indirectly) called from the ApplicationKernel
constructor, making setting the application root from the Bootstrap class
impossible.
In addition, this method will be needed in the Composer ScriptHandler class,
which should not need to bootstrap the application.
=> [CLEANUP] Move getApplicationRoot to a separate class

Classes/Core/ApplicationKernel.php, Classes/Core/ApplicationStructure.php, Tests/Integration/Core/ApplicationKernelTest.php, Tests/Unit/Core/ApplicationStructureTest.php
The term "project root" is misleading for cases where the application kernel
comes from a dependency (as it is the case with phpList 4).
This change is necessary so packages like rest-api still can load the core
configuration.
=> [BUGFIX] Symfony project root always needs to be the core package root

Classes/Core/Bootstrap.php
This fixes an "access denied" message when loading the development
entry point on a local development system.
=> [BUGFIX] Have local requests as a sign of a development server

Classes/Core/Bootstrap.php, Classes/Core/Environment.php, Configuration/PHPMD/rules.xml, Tests/Integration/ApplicationBundle/Controller/DefaultControllerTest.php, Tests/Integration/Core/ApplicationKernelTest.php, Tests/Integration/Core/BootstrapTest.php, Tests/Integration/Domain/Repository/AbstractRepositoryTest.php, Tests/Unit/Core/ApplicationKernelTest.php, Tests/Unit/Core/BootstrapTest.php, Tests/Unit/Core/EnvironmentTest.php, bin/console, web/app_dev.php, web/app_test.php
This resolves a circular dependency between Bootstrap and ApplicationKernel.
Also unify the terminology from "application context" to "environment" to
be closer to Symfony conventions.
=> [CLEANUP] Add an Environment class

Configuration/config.yml, Configuration/config_dev.yml, Configuration/config_prod.yml, Configuration/config_test.yml, Configuration/parameters.yml, Configuration/routing_dev.yml, Configuration/routing_prod.yml, Configuration/routing_test.yml, Configuration/services.yml
Now the configuration is basically the same as the default configuration
of new Symfony projects (except for the parts which phpList is not using
yet).
=> [CLEANUP] Follow the Symfony configuration conventions more closely

Classes/Core/ApplicationKernel.php
The return type hints for some public and private must not be present
so the method signatures do not clash with the generated cached subclasses
(which do not have the return type hints).
=> [BUGFIX] Fix ApplicationKernel method signatures

Classes/Composer/ScriptHandler.php
The configuration file needs to be located in the application root, not
in the project root, moving the configuration file out of the vendor/
folder for cases where phplist4-core is used as a library.
This is a follow-up fix to #158.
=> [BUGFIX] Create the bundle configuration in the correct location

Classes/Composer/ScriptHandler.php
Although not writing the file in binary mode does not create any errors,
it still is recommended to always write files in binary mode.
=> [BUGFIX] Always write the bundle configuration file in binary mode

Classes/Composer/ModuleBundleFinder.php, Tests/Integration/Composer/ScriptsTest.php, Tests/Unit/Composer/ModuleBundleFinderTest.php
- don't quote strings that do not need to be quoted
- provide an empty hash if there is no data
This is a prerequisite to using the Symfony YAML component for
generating YAML files.
=> [TASK] Clean up the generated YAML bundle configuration file

Tests/Unit/Composer/ModuleBundleFinderTest.php
This should make the tests a bit more readable for persons who are
not familiar with the ASCII value of a linefeed.
=> [CLEANUP] Use \n instead of chr(10) for linefeeds in the tests

Configuration/PHPMD/rules.xml
We don't have the $lf variable anymore and hence don't need to whitelist
it in the PHPMD configuration anymore.
=> [CLEANUP] Remove the "lf" short variable name whitelisting

Classes/Core/Bootstrap.php, Tests/Integration/Core/BootstrapTest.php, web/app_dev.php, web/app_test.php
The old name was awkward, hard to understand and kind of
reverse-logic.
=> [CLEANUP] Rename Bootstrap::preventProductionEnvironment

Tests/Unit/Composer/ModuleBundleFinderTest.php
The new name now better reflects that the corresponding method is
about module configuration, not just bundle configuration.
=> [CLEANUP] Rename method in unit test

Configuration/config.yml
This is required for the switching the REST API to the
FOSRestBundle.
=> [TASK] Enable the Symfony serializer

Classes/Composer/PackageRepository.php, Tests/Unit/Composer/PackageRepositoryTest.php
If a package has a branch alias, it should not be listed twice when
using composer run-script list-modules.
=> [BUGFIX] list-modules should ignore branch aliases

.gitignore, Classes/Composer/ScriptHandler.php, Classes/Core/ApplicationKernel.php, Configuration/config.yml, Configuration/parameters.yml, Configuration/parameters_template.yml, Tests/Integration/Composer/ScriptsTest.php, composer.json
parameters.yml will contain installation-specific data and must not be
overwritten on a composer update. Hence, it needs to reside in the
Configuration/ folder of the application, not in the Configuration/
folder of the core package (will will get overwritten on an update).
Also automatically create the file on a composer install/update
(if the file does not exist yet).
This change is a prerequisite to switching to the Symfony Doctrine
integration.
=> [FEATURE] Move the parameters.yml outside of the vendor/folder

Tests/Integration/Core/BootstrapTest.php, Tests/Unit/Core/BootstrapTest.php
- move a test that really is a unit test into the unit test case
- reorder some tests make the test case easier to understand
This cleanup will help make the Doctrine-Symfony integration PR
smaller.
=> [CLEANUP] Move some Bootstrap tests around

Configuration/config.yml
The session data should be stored in var/sessions/ in the application
root, not in the phplist4-core directory within vendor/.
Fixes #195
=> [BUGFIX] Store the session data outside vendor/

Tests/Unit/Composer/ModuleFinderTest.php
This cleanup is a preparation for module-provided system configuration,
which in turn is a prerequisite for using the FOSRestBundle for the
rest-api module.
=> [CLEANUP] Extract creating modules for data provides

Configuration/config.yml, Configuration/parameters_template.yml
This will make sure people will already have placeholders in their
parameters.yml when we provide SQLite support, making the transition
easier.
=> [TASK] Add a configuration for the database path

Configuration/services.yml, Tests/Integration/Core/ApplicationStructureTest.php, Tests/Integration/EmptyStartPageBundle/Controller/DefaultControllerTest.php, Tests/Integration/Security/HashGeneratorTest.php
- always use the class name as service name
- always register controllers as services and them for action injection
This makes the service configuration closer to the Symfony 3.3 defaults.
=> [CLEANUP] Cleanup up the service configuration

Classes/Domain/Repository/AbstractRepository.php, Classes/Domain/Repository/Identity/AdministratorRepository.php, Classes/Domain/Repository/Identity/AdministratorTokenRepository.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
This method allows controllers to not depend on the entity manager,
but only on the repositories instead, following the Law of Demeter.
=> [FEATURE] AbstractRepository.save

.gitignore, Classes/Composer/ModuleFinder.php, Classes/Composer/ScriptHandler.php, Classes/Core/ApplicationKernel.php, README.md, Tests/Integration/Composer/ScriptsTest.php, Tests/Unit/Composer/ModuleFinderTest.php, composer.json
This change is a prerequisite for switching the rest/api module to the
FOSRestBundle bundle.
=> [FEATURE] System configuration from modules

Classes/Core/ApplicationKernel.php
This will make sure that the configuration file works when the
core package is used as a library.
=> [BUGFIX] Load the module-provided config from application root

Classes/Domain/Repository/Identity/AdministratorRepository.php, Configuration/config.yml, Configuration/repositories.yml, Configuration/services.yml
- mark the setter injection of the HashGenerator in the AdministratorRepository
as @required, which allows us to remove the DI configuration from services.yml
- use an abstract service for all repositories and move the definitions of the
repository services into a separate file (which is necessary for them to have
the abstract service as parent)
- drop optional quotes from the tags of the controller so the tag definitions
are consistent
=> [CLEANUP] Clean up the service definitions

Classes/Domain/Model/Traits/IdentityTrait.php
This will allow having models that use the Identity trait, but do not use
any other @Column annotations themselves.
=> [CLEANUP] Add the @Column annotation to the Identity trait

Classes/Domain/Model/Identity/Administrator.php, Classes/Domain/Model/Interfaces/CreationDate.php, Classes/Domain/Model/Interfaces/ModificationDate.php, Classes/Domain/Model/Traits/CreationDateTrait.php, Classes/Domain/Model/Traits/IdentityTrait.php, Classes/Domain/Model/Traits/ModificationDateTrait.php
Also make the affected properties in the Administrator model
protected instead of private so that the static code analysis
will not mark them as unused.
=> [CLEANUP] Traits for creation and modification dates

Configuration/config.yml, composer.json
This allows us to easily convert entities to JSON in responses,
e.g., in the REST API.
=> [TASK] Switch from the Symfony serializer to JMS serializer

Configuration/PHPMD/rules.xml
The class needs to be accessed statically, and we need PHPMD to not
complain about this.
=> [TASK] Whitelist the FOSRestBundle view class for static access

Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php, Tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php, Tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
The previous semi-automatic renaming was too eager and had renamed all
*RepositoryTest to *DatabaseTest. This change now is reverted.
=> [CLEANUP] Fix the names of repository integration tests

Configuration/config_dev.yml, Configuration/config_prod.yml, composer.json
This change gets Monolog to log to a file when running the integration
tests instead of spamming the console with the log messages, making
problems in the tests and error messages easier to spot.
This change does not add any additional logging, though.
=> [TASK] Monolog configuration

Classes/Domain/Model/Identity/AdministratorToken.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
The creation date is saved in the database as a UNIX timestamp
and thus does not contain a time zone. This causes the timestamp
to result in different dates depending on the time zone set in
the PHP configuration, leading to test failures on some systems.
Now the timestamp will always be interpreted to be in the UTC
timezone.
=> [BUGFIX] Always use UTC as token creation date time zone

Classes/TestingSupport/Traits/ContainsInstanceAssertionTrait.php, Classes/TestingSupport/Traits/ModelTestTrait.php, Classes/TestingSupport/Traits/SimilarDatesAssertionTrait.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php, Tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php, Tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php, Tests/Unit/Core/ApplicationKernelTest.php, Tests/Unit/Domain/Model/Identity/AdministratorTest.php, Tests/Unit/Domain/Model/Identity/AdministratorTokenTest.php, Tests/Unit/Domain/Model/Messaging/SubscriberListTest.php, Tests/Unit/Domain/Model/Subscription/SubscriberTest.php
This makes the traits available in non-development installations, i.e.,
also for packages that require this package.
=> [TASK] Move test support traits to Classes/

Tests/System/ApplicationBundle/PhpListApplicationBundleTest.php
Now, an error HTTP status code can also be checked for in the system
tests (instead of throwing an exception).
This currently is not needed yet, but should be consistent to the system
tests of the rest-api package (where this is needed).
=> [BUGFIX] Adapt the system tests to possible HTTP errors

Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php
The test findOneByLoginCredentialsForMatchingCredentialsReturnsModel
was not loading the database fixtures, causing the test to fail when
executed stand-alone (or when executed together with other tests when
the database tables got properly truncated on tearDown).
=> [BUGFIX] Load database fixture in AdministratorRepositoryTest

Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php, Tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php
After the fixes for properly truncating tables in the tests, touchDatabaseTable works fine and can always be used.
=> [CLEANUP] Always use touchDatabaseTable in the integration tests

CHANGELOG.md, src/Domain/Model/Messaging/SubscriberList.php, src/Domain/Model/Subscription/Subscriber.php, tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php, tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
When a subscriber or a subscriber list is removed, all associated
subscriptions need to be removed as well.
=> [BUGFIX] Cascading removal of subscriptions

CHANGELOG.md, tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php, tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
The tests used the wrong variable names and only were green
by pure coincidence.
=> [FOLLOWUP] Use correct association count in tests for cascading removal

composer.json
Composer tries to install doctrine/instantiator 1.1.0 on PHP 7.0,
but this version requires PHP ^7.1. This seems to be a bug in Composer,
and setting the doctrine/instantiator version ^1.0.0 will work around
this problem.
=> [BUGFIX] Fix Composer-related build failure with PHP 7

CHANGELOG.md, src/Domain/Repository/AbstractRepository.php, tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php, tests/Integration/Domain/Repository/Messaging/SubscriberListRepositoryTest.php, tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php, tests/Integration/Domain/Repository/Subscription/SubscriptionRepositoryTest.php
This allows the removal of entities from controllers without
needing a refererence to the entity manager.
Also remove two redundant touchDatabaseTable calls from the integration
tests.
=> [FEATURE] Repository.remove

config/PhpCodeSniffer/ruleset.xml
Fixes the following error message on current master:
```
$ echo; echo "Running PHP_CodeSniffer"; vendor/bin/phpcs --standard=config/PhpCodeSniffer/ bin/ src/ tests/ public/;
Running PHP_CodeSniffer
ERROR: Referenced sniff "Squiz.PHP.ForbiddenFunctions" does not exist
Run "phpcs --help" for usage information
The command "echo; echo "Running PHP_CodeSniffer"; vendor/bin/phpcs --standard=config/PhpCodeSniffer/ bin/ src/ tests/ public/;
" exited with 3.
``` 
There is still another error on master which I will fix in another PR.
Compare also the error output of https://travis-ci.org/phpList/core/jobs/395079478 with https://travis-ci.org/phpList/core/jobs/395081943
=> Remove not existing Squiz.PHP.ForbiddenFunctions

composer.json
There is a known bug in Composer (https://github.com/composer/composer/issues/7388) which makes ``--prefer-lowest` pull in a version incompatible with PHP 7.0.
Until this issue is resolved, let's hardcode 1.0.5 as dependency.
See also https://travis-ci.org/phpList/core/jobs/395091949 which is working vs. https://travis-ci.org/phpList/core/jobs/395081946 which is not.
=> Hardcode doctrine/instantiator 1.0.5 as dependency

src/Domain/Model/Messaging/SubscriberList.php
Useful for: https://github.com/phpList/rest-api/pull/116
The "count" function on the collection can be called without triggering a full load of the collection in the memory. More info: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/tutorials/extra-lazy-associations.html
Signed-off-by: Xheni Myrtaj <myrtajxheni@gmail.com>
=> Mark subscribers association as extra lazy.

config/config_test.yml, src/Domain/Analytics/Model/LinkTrackForward.php, src/Domain/Configuration/Model/I18n.php, src/Domain/Configuration/Model/UrlCache.php, src/TestingSupport/Traits/DatabaseTestTrait.php, tests/Integration/Domain/Identity/Repository/AdministratorRepositoryTest.php
- change test db to mysql
- updated column lengths to be possible to create schema for tests
=> change test db

config/packages/messenger.yaml, config/parameters.yml.dist, config/services.yml, config/services/managers.yml, config/services/messenger.yml, config/services/services.yml, src/Domain/Messaging/Message/SubscriberConfirmationMessage.php, src/Domain/Messaging/MessageHandler/SubscriberConfirmationMessageHandler.php, src/Domain/Messaging/Service/EmailService.php, src/Domain/Subscription/Service/Manager/SubscriberManager.php, tests/Unit/Domain/Messaging/Message/SubscriberConfirmationMessageTest.php, tests/Unit/Domain/Messaging/MessageHandler/SubscriberConfirmationMessageHandlerTest.php, tests/Unit/Domain/Subscription/Service/SubscriberManagerTest.php
- send subscription confirmation email
Related: #12
=> ISSUE-12: subscription confirmation email

src/Domain/Subscription/Model/Dto/SubscriberImportOptions.php, src/Domain/Subscription/Service/Manager/SubscriberAttributeManager.php, src/Domain/Subscription/Service/Manager/SubscriberManager.php, src/Domain/Subscription/Service/SubscriberCsvImporter.php, tests/Unit/Domain/Subscription/Service/SubscriberAttributeManagerTest.php, tests/Unit/Domain/Subscription/Service/SubscriberCsvImportManagerTest.php
- Add a dryRun option to subscriber csv import that will not persist data in DB
style?
=> Add a dryRun option to subscriber csv import
