core/Admin.php, core/Campaign.php, core/Model/AdminModel.php, core/Model/ListModel.php, core/Model/SubscriberModel.php, core/SubscriberManager.php, core/helper/PrepareCampaign.php, core/helper/String.php, core/helper/Util.php, core/phpListMailer.php
There is a problem with a helper class named String. This is a reserved name on PHP7. This is a PHP7 specific problem.
=> fixed String problem on PHP7

.travis.yml
- lint the PHP files
- run the unit tests
=> [TASK] Add a basic .travis.yml

LICENSE, README.md
=> [TASK] Add a LICENSE file (Affero GPL V3)

composer.json
Now the indentation is 2 spaces, thus making this consistent with PSR-2.
=> [CLEANUP] Autoformat the composer.json

.travis.yml, config.ini.dist
The tests currently will still fail as there is not data yet in the DB.
This will come as a next step.
=> [TASK] Add a database connection to Travis CI

README.md
Also use the term "module" consistently.
=> [TASK] Add DB schema changes and plugins to the README

composer.json, core/tests/EmailUtilTest.php, core/tests/PassTest.php
Note: Before this PR can be merged, #44 and #45 must be merged, and I will need to rebase this PR.
=> [TASK] Update to PHPUnit 6

.github/PULL_REQUEST_TEMPLATE.md
=> [TASK] Add a pull request template

README.md, composer.json
- change the type from "project" to the custom "phplist-module"
- use the short form for the license
- update support URLs
- add the roave/security-advisories repository to check for
security vulnerabilities
- reorder the sections to be in the same order as in the
Composer reference
- add myself as an author
Also update the Travis status icon to the new repository name
phplist4-core.
=> [TASK] Streamline the composer.json

.travis.yml
- also cache the composer cache
- disable Xdebug
- also make the .travis.yml easier to read
=> [TASK] Configure Travis for faster builds

.travis.yml, Classes/Core/Bootstrap.php, Tests/Unit/Core/BootstrapTest.php, composer.json
Later commits will add more functionality to the Bootstrap class.
=> [FEATURE] Add a system bootstrap

composer.json
Also consistently use the ^ notation for version numbers and always use
three-segment version numbers.
=> [TASK] Update Composer dependencies

.travis.yml, Database/Schema.sql, README.md
Now Travis import the database schema before each build.
The database schema has been taken from the development demo database
(but without the data).
=> [FEATURE] Add and import the database schema

.travis.yml, Configuration/PHPMD/rules.xml, composer.json
This one is blocked by #76 as I need to make sure that the added code will not create any PHPMD warnings.
=> [FEATURE] Add PHPMD sniffing with a custom rule set

.travis.yml, Classes/Domain/Model/Identity/AdministratorToken.php, Classes/Domain/Repository/Identity/AdministratorTokenRepository.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/Fixtures/DetachedAdministratorToken.csv, Tests/Unit/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php, composer.json
Also hook up the existing AdministratorToken model to Doctrine ORM.
=> [FEATURE] Add an AdministratorToken repository

.github/CONTRIBUTING.md, README.md
- link CONTRIBUTING.md from the README
- differentiate between unit tests and integration tests
- document how to run the integration tests
- document to use the stricter standard for PHP_CodeSniffer
- document how to run PHPMD
=> [TASK] Improve the contribution documentation

.travis.yml
The CI steps are now ordered to give feedback on functionality first,
then on code structure, then on style. In addition, newer code is checked
first.
This will help make the CI give the most relevenat feedback first during
development.
=> [TASK] Reorder the CI steps

.github/CONTRIBUTING.md, .travis.yml, Classes/Core/Bootstrap.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php, composer.json
Also enhance the type annotations of two fields to be more correct.
=> [FEATURE] Check the code using static analysis

Classes/Domain/Model/Identity/Administrator.php, Classes/Domain/Repository/Identity/AdministratorRepository.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/Fixtures/DetachedAdministrator.csv, Tests/Unit/Domain/Model/Identity/AdministratorTest.php, Tests/Unit/Domain/Repository/Identity/AdministratorRepositoryTest.php
The AdministratorToken-Administrator association will come in a later
commit.
Additional business logic for the Administrator model will also come in
later commits.
=> [FEATURE] Administrator model and repository

README.md, core/Config.php, core/phpListMailer.php
Also fix a minor formatting issue in the README.
=> [BUGFIX] Use HTTPS for all phplist.com URLs

Tests/Support/Traits/ModelTestTrait.php, Tests/Support/Traits/SimilarDatesAssertionTrait.php, Tests/Unit/Domain/Model/Identity/AdministratorTest.php, Tests/Unit/Domain/Model/Identity/AdministratorTokenTest.php
Also move the ModelTestTrait to the new Tests\Support namespace.
=> [CLEANUP] Provide an assertSimilarDates assertion

Classes/Domain/Model/Identity/Administrator.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/Fixtures/Administrator.csv, Tests/Unit/Domain/Model/Identity/AdministratorTest.php
This property is automatically updated when the password has gets set.
=> [FEATURE] Add Administrator.passwordChangeDate

Tests/Integration/Domain/Repository/AbstractRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php
- drop redundant entityManager repository in subclass
- switch the order of setUp commands to have related things closer together
=> [CLEANUP] Clean up the repository integration tests

Documentation/ClassStructure.md, README.md
Also mention that the models and repositories might need to be
changed for database changes.
=> [TASK] Document the current class structure

Classes/Domain/Repository/Identity/AdministratorTokenRepository.php, Configuration/PhpCodeSniffer/ruleset.xml, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php
Also remove an incorrect PHP_CodeSniffer rule that clashes with the new code.
=> [FEATURE] AdministratorTokenRepository.removeExpired

Classes/Core/Bootstrap.php, Tests/Integration/Domain/Repository/AbstractRepositoryTest.php, Tests/Unit/Core/BootstrapTest.php
There are three possible application contexts now:
- Production (for live sites)
- Testing (for automated tests)
- Development (for local development)
These contexts allow for more fine-grained application behavior.
The application contexts replace the development mode of the Bootstrap
class.
=> [FEATURE] Application contexts

Configuration/PHPMD/rules.xml
This will reduce the size of commits that add whitelisting for single rules.
=> [TASK] List individual rules in the PHPMD configuration

Classes/Core/ApplicationKernel.php, Classes/Routing/ExtraLoader.php, Configuration/Environments/Development.yml, Configuration/Environments/Production.yml, Configuration/Environments/ProductionRouting.yml, Configuration/Environments/Testing.yml, Configuration/Environments/TestingRouting.yml, Configuration/PHPMD/rules.xml, Configuration/PhpCodeSniffer/ruleset.xml, Configuration/Routing.yml, Configuration/Services.yml, Tests/Unit/Routing/ExtraLoaderTest.php
Now the core will use the REST bundle and its routing if the bundle
is installed.
Also tweak the PHPCS rules as needed.
=> [FEATURE] Allow using the REST bundle

.travis.yml
This fixes the build if Travis is using the new Trusty image.
=> [BUGFIX] Fix MySQL with the new Trusty Travis images

composer.json
Now the branch alias name is following the usual Composer conventions.
=> [TASK] Rename the branch alias "4.0.0.x-dev" to "4.0.x-dev"

Public/.htaccess
This is the default .htaccess for Symfony projects.
=> [TASK] Add a .htaccess to the Public/ directory

Classes/Core/ApplicationKernel.php, README.md, Tests/Support/Traits/ContainsInstanceAssertionTrait.php, Tests/Unit/Core/ApplicationKernelTest.php, composer.json
The server can be started using this command:
bin/console server:run
Also document the use of the different environments.
=> [FEATURE] Development and testing web server

Classes/Composer/PackageRepository.php, Tests/Unit/Composer/PackageRepositoryTest.php, composer.json
This is the first step towards getting a list of installed phpList modules.
=> [FEATURE] Composer PackageRepository

Classes/Core/ApplicationKernel.php, Classes/Core/ApplicationStructure.php, Configuration/PHPMD/rules.xml, Configuration/bundles.yml
Also adapt the PHPMD configuration file to allow static access to the
YAML class.
=> [FEATURE] Bundle configuration file

Tests/Unit/Composer/ModuleBundleFinderTest.php
This helps as avoid having to manually write YAML that can easily
be constructed from PHP arrays instead.
=> [CLEANUP] Use the Symfony Yaml class in the unit tests

composer.json
This is a prerequisite for automatically clearing the caches
during installation and updates.
=> [TASK] Add Symfony-related directory configuration to composer.json

Classes/ApplicationBundle/Controller/DefaultController.php, README.md, Tests/Integration/Composer/ScriptsTest.php, Tests/Integration/Routing/ExtraLoaderTest.php, composer.json
This will reduce the amount of configuration needed in the composer.json.
=> [CLEANUP] Use annotations to define the routes

Classes/Composer/ScriptHandler.php, composer.json
Also warm the production cache.
=> [WIP][FEATURE] Clear the Symfony caches on a composer install/update

Configuration/parameters_template.yml
This will increase security for production environment as then an attacker
cannot find out the secret with read-only access to the files.
Documentation for this will be in the base_distribution package.
=> [FEATURE] Allow setting the secret with an environment variable

Classes/Core/Bootstrap.php
Now the method order will be a bit more intuitive, making the class easier
to read.
This is preparation PR to the Doctrine-Symfony integration.
=> [CLEANUP] Reorder the Bootstrap methods

Classes/Core/Bootstrap.php, Classes/Domain/Repository/Identity/AdministratorRepository.php, Configuration/config_test.yml, Configuration/services.yml, README.md, Tests/Integration/Core/BootstrapTest.php, Tests/Integration/Domain/Repository/AbstractRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorRepositoryTest.php, Tests/Integration/Domain/Repository/Identity/AdministratorTokenRepositoryTest.php, Tests/Integration/Security/HashGeneratorTest.php, Tests/Unit/Core/BootstrapTest.php
Also provide the existing two repositories as services.
=> [TASK] Use the Symfony dependency injection for the HashGenerator

Classes/Domain/Model/Messaging/SubscriberList.php
This configuration configures the fields visible in the REST API.
=> [TASK] Configure the SubscriberList fields exposed by APIs

Classes/Domain/Repository/Subscription/SubscriberRepository.php, Tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php
This method will be used to check for duplicates when creating
new subscribers.
=> [FEATURE] SubscriberRepository.findOneByEmail

Classes/Composer/ScriptHandler.php
This also fixes composer create-project.
Fixes #194
=> [BUGFIX] Do no depend on a valid configuration for clearing the caches

.github/CONTRIBUTING.md, README.md
This enables syntax highlighting when rendering the README.
Also update the copyright year.
=> [TASK] Provide the code language in the code snippets in the README

Configuration/PhpCodeSniffer/ruleset.xml, composer.json
Also add helpful new sniffs to our rule set.
=> [TASK] Update PHPUnit and PHP_CodeSniffer

Tests/System/ApplicationBundle/PhpListApplicationBundleTest.php
This makes the code more concise.
=> [CLEANUP] Use Guzzle's convenience methods in the system tests

CHANGELOG.md, src/Domain/Model/Identity/Administrator.php, src/Domain/Model/Identity/AdministratorToken.php, src/Domain/Model/Interfaces/DomainModel.php, src/Domain/Model/Messaging/SubscriberList.php, src/Domain/Model/Subscription/Subscriber.php, src/Domain/Model/Subscription/Subscription.php, src/Domain/Repository/AbstractRepository.php, tests/Unit/Domain/Model/Identity/AdministratorTest.php, tests/Unit/Domain/Model/Identity/AdministratorTokenTest.php, tests/Unit/Domain/Model/Messaging/SubscriberListTest.php, tests/Unit/Domain/Model/Subscription/SubscriberTest.php, tests/Unit/Domain/Model/Subscription/SubscriptionTest.php
This interface removes the need to have the generic "object" type
for methods that use a domain model.
=> [FEATURE] Interface for domain models

CHANGELOG.md, README.md, composer.json, src/Composer/ModuleFinder.php, src/Composer/ScriptHandler.php, src/Core/ApplicationKernel.php, src/Core/ApplicationStructure.php, src/Core/Bootstrap.php, tests/Integration/Composer/ScriptsTest.php, tests/Support/Interfaces/TestMarker.php, tests/Unit/Composer/ModuleFinderTest.php, tests/Unit/Composer/PackageRepositoryTest.php, tests/Unit/Composer/ScriptHandlerTest.php
Changed composer.json to reflect the updated repository name following discussion here in://github.com/phpList/core/issues/273
=> Change the package name to phplist/core

CHANGELOG.md, src/Domain/Repository/Subscription/SubscriptionRepository.php, tests/Integration/Domain/Repository/Fixtures/Subscriber.csv, tests/Integration/Domain/Repository/Subscription/SubscriptionRepositoryTest.php
This makes it possible to retrieve an existing subscription, e.g.,
for removing it.
=> [FEATURE] SubscriptionRepository.findOneBySubscriberListAndSubscriber

src/Domain/Model/Subscription/Subscriber.php, tests/Integration/Domain/Repository/Fixtures/Subscriber.csv, tests/Integration/Domain/Repository/Subscription/SubscriberRepositoryTest.php, tests/Unit/Domain/Model/Subscription/SubscriberTest.php
I added the missing extradata get and set functions to subcriber class since extradata is a field of user table.
=> Add missing extradata functions to subscriber class

resources/Database/Schema.sql
Removed duplicated user history table.
=> Remove duplicated table in schema

resources/Database/Schema.sql
=> Update db Schema with the latest changes from phpList3

.github/workflows/ci.yml, src/TestingSupport/Traits/DatabaseTestTrait.php
Implemented new CI/CD strategy using `github workflows`.
Unit tests validated
Integration tests initially failed due on github workflow due to a change on environment, where port and host settings matters.
- [Successful run without integration tests](https://github.com/Fenn-CS/core/actions/runs/537223712)
- [Failed run (current state) including integration tests](https://github.com/Fenn-CS/core/actions/runs/537252142)
Integration tests pass
https://github.com/Fenn-CS/core/actions/runs/541728848
=> added github workflow for builds and tests

README.md
Provide a general description of the code changes in your pull request …
were there any bugs you had fixed? If so, mention them. If these bugs have open
GitHub issues, be sure to tag them here as well, to keep the conversation
linked together.
style?
If you are updating any of the CHANGELOG files or are asked to …
=> Updated copyright date

src/Domain/Repository/Subscription/SubscriberRepository.php
- update function return type for static analysis
=> ISSUE-344: api updates

composer.json, config/services/managers.yml, config/services/providers.yml, config/services/repositories.yml, config/services/services.yml, src/Domain/Messaging/Command/ProcessQueueCommand.php, src/Domain/Messaging/Model/Message.php, src/Domain/Messaging/Repository/ListMessageRepository.php, src/Domain/Messaging/Repository/MessageRepository.php, src/Domain/Messaging/Service/MessageProcessingPreparator.php, src/Domain/Subscription/Repository/SubscriberRepository.php, src/Domain/Subscription/Service/Provider/SubscriberProvider.php, tests/Unit/Domain/Messaging/Command/ProcessQueueCommandTest.php, tests/Unit/Domain/Messaging/Service/MessageProcessingPreparatorTest.php, tests/Unit/Domain/Subscription/Service/Provider/SubscriberProviderTest.php
- process queued campaigns command
=> Process queue command

src/Domain/Messaging/Repository/ListMessageRepository.php
Fix property name in repository function 
style?
=> Fix prop name in repo

src/Domain/Subscription/Model/Filter/SubscriptionHistoryFilter.php, src/Domain/Subscription/Repository/SubscriberHistoryRepository.php, src/Domain/Subscription/Service/SubscriptionHistoryService.php, tests/Unit/Domain/Subscription/Service/SubscriptionHistoryServiceTest.php
- add subscriber history service (to use in rest-api endpoint)
style?
=> Subscriber history service

config/config_prod.yml, src/Domain/Subscription/Model/Dto/ImportSubscriberDto.php, src/Domain/Subscription/Service/Manager/SubscriberManager.php, src/Domain/Subscription/Service/SubscriberCsvImporter.php
- fix import
- temporarily disable graylog  
style?
=> Fix import

src/Domain/Messaging/Model/Message.php, src/Domain/Messaging/Repository/ListMessageRepository.php, src/Domain/Messaging/Repository/MessageRepository.php, src/Domain/Messaging/Service/Manager/ListMessageManager.php, src/Domain/Subscription/Model/SubscriberList.php, src/Domain/Subscription/Repository/SubscriberListRepository.php, src/Domain/Subscription/Service/Provider/SubscriberProvider.php, tests/Unit/Domain/Messaging/Service/ListMessageManagerTest.php, tests/Unit/Domain/Subscription/Service/Provider/SubscriberProviderTest.php
- get from message and subscriber list repositories
- fix repository function relation
style?
=> List message repo
